---
title: "Data Cleaning"
author: "Janet Li"
format: pdf
---

```{r}
#| message: false
library(tidyverse)
library(brms)
options(brms.backend = "cmdstanr")
library(bayesplot)
library(here)
```

# Demographics

```{r}
MDD <- read_csv("MDD_all.csv", show_col_types = FALSE)
flanker_all <- read_csv("compiled-flanker-data.csv", show_col_types = FALSE)
# remove rows for test runs (i.e., where subject ID starts with 9)
flanker_all <- flanker_all %>% filter(grepl('^[1-8]', subject_id))
extra_IDs <- c(3963, 3970, 3981, 3983, 3985, 3989, 4002, 117)
IDs_all <- c(flanker_all$subject_id, extra_IDs)
# PARCS: UIC 15, USC 14
MDD_CARS <- MDD %>% filter(ID %in% IDs_all)
sum(MDD_CARS$MDDnew)
```

# Concatenate data across subjects for each task

## Global Parameters

```{r}
study <- "PARC" # CAR or PARC
school <- "USC"
if (school == "UIC") {
  basefolder <- paste0("../Examiner/", study, "_", school, "_Examiner")
} else {
  if (study == "CAR") {
    basefolder <- paste0("../../../", study, " Study/Data/Visit 2 Data")
  } else {
    basefolder <- paste0("../../../", study, " Study/Data/Visit 2")
  }
}
```

```{r}
# no data: 
# CARS UIC: 2959
IDs <- list.files(basefolder)
IDs <- IDs[nchar(IDs) < 5 & !is.na(as.integer(IDs))]
IDs <- IDs[as.integer(IDs) < 8000]
tasks <- c("Flanker", "NBack", "SetShifting")
flanker <- c()
nback <- c()
setshifting <- c()
no_data <- setNames(data.frame(matrix(ncol = 2, nrow = 0)), c("ID", "task"))

for (id in IDs) {
  print(paste0("Working on ", id))
  folder <- paste0(basefolder, "/", id, "/Examiner")
  if (id %in% list.files(folder)) {
    folder <- paste0(folder, "/", id)
  }
  allfiles <- list.files(folder)
  if (length(allfiles) == 0) {
    print(paste0("No data for ", id, ", skipping them."))
    no_data[nrow(no_data)+1, ] <- c(id, "all")
    next
  }
  for (task in tasks) {
    print(task)
    filename <- allfiles[str_detect(allfiles, paste0(task, "_", id))]
    if (length(filename) == 0) {
      print(paste0("No ", task, " data for ", id, ", skipping them."))
      no_data[nrow(no_data)+1, ] <- c(id, task)
      next
    }
    data <- read_csv(paste0(folder, "/", filename), show_col_type = FALSE)
    if (task == "Flanker") {
      flanker <- rbind(flanker, data)
    }
    if (task == "NBack") {
      nback <- rbind(nback, data)
    }
    if (task == "SetShifting") {
      setshifting <- rbind(setshifting, data)
    }
  }
  print(paste0(id, " finished."))
}
```

```{r}
flanker_filename <- paste0('../Examiner/', study, "_", school, "_flanker_all.csv")
nback_filename <- paste0('../Examiner/', study, "_", school, "_nback_all.csv")
setshifting_filename <- paste0('../Examiner/', study, "_", school, "_setshifting_all.csv")
no_data_filename <- paste0('../Examiner/', study, '_', school, "_nodata.csv")

write_csv(flanker, flanker_filename)
write_csv(nback, nback_filename)
write_csv(setshifting, setshifting_filename)
write_csv(no_data, no_data_filename)
```
